<?php

/**
 * @file
 * Schema definitions install/update/uninstall hooks.
 */

/**
 * Implements hook_schema().
 */
function push_hub_schema() {
  $schema = array();
  $schema['push_hub_subscriptions'] = array(
    'description' => 'PubsubHubbub subscriptions.',
    'fields' => array(
      'timestamp' => array(
        'type' => 'int',
        'unsigned' => FALSE,
        'default' => 0,
        'not null' => TRUE,
        'description' => 'Created timestamp.',
      ),
      'secret' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Shared secret for message authentication.',
      ),
      'topic' => array(
        'type' => 'text',
        'not null' => TRUE,
        'description' => 'The topic URL (feed URL) of this subscription.',
      ),
      'subscriber' => array(
        'type' => 'text',
        'not null' => TRUE,
        'description' => 'The subscriber\'s notification URL.',
      ),
    ),
    'indexes' => array(
      'timestamp' => array('timestamp'),
      'topic' => array(array('topic', 255)),
      'topic_subscriber' => array(array('topic', 128), array('subscriber', 128)),
    ),
  );
  return $schema;
}

/**
 * Implements hook_install().
 */
function push_hub_install() {
  // Create tables.
  // TODO The drupal_(un)install_schema functions are called automatically in D7.
  // drupal_install_schema('push_hub')
}

/**
 * Implements hook_uninstall().
 */
function push_hub_uninstall() {
  // Remove tables.
  // TODO The drupal_(un)install_schema functions are called automatically in D7.
  // drupal_uninstall_schema('push_hub')
}

/**
 * Add a table for Pubsub subscriptions.
 */
function push_hub_update_6001() {
  $ret = array();
  $table = array(
    'description' => 'PubsubHubbub subscriptions.',
    'fields' => array(
      'timestamp' => array(
        'type' => 'int',
        'unsigned' => FALSE,
        'default' => 0,
        'not null' => TRUE,
        'description' => 'Created timestamp.',
      ),
      'topic' => array(
        'type' => 'text',
        'not null' => TRUE,
        'description' => t('The topic URL (feed URL) of this subscription.'),
      ),
      'subscriber' => array(
        'type' => 'text',
        'not null' => TRUE,
        'description' => t('The subscriber\'s notification URL.'),
      ),
    ),
    'indexes' => array(
      'timestamp' => array('timestamp'),
      'topic' => array(array('topic', 255)),
      'topic_subscriber' => array(array('topic', 255), array('subscriber', 255)),
    ),
  );
  db_create_table('push_hub_subscriptions', $table);
  // hook_update_N() no longer returns a $ret array. Instead, return
  // nothing or a translated string indicating the update ran successfully.
  // See http://drupal.org/node/224333#update_sql.
  return t('TODO Add a descriptive string here to show in the UI.') /* $ret */;
}
